export const PROCESSES_SAVE = 'PROCESS/SAVE'
export const PROCESSES_GET = 'PROCESS/GET'
export const PROCESSES_REMOVE = 'PROCESS/REMOVE'
export const PROCESSES_UPDATE_RUNNING = 'PROCESS/UPDATE_RUNNING'
